"""altercao option value

Revision ID: 1217727e026b
Revises: 7268d60ea959
Create Date: 2024-02-07 15:32:45.237003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1217727e026b'
down_revision = '7268d60ea959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
