"""Tabela Usuario

Revision ID: 40261ba6ca75
Revises: 0173037c94f4
Create Date: 2024-01-12 13:36:52.718483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40261ba6ca75'
down_revision = '0173037c94f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
