"""posto,entity,field,option

Revision ID: 7268d60ea959
Revises: 40261ba6ca75
Create Date: 2024-02-07 14:15:32.424099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7268d60ea959'
down_revision = '40261ba6ca75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('attend_expiration', sa.DateTime(), nullable=True),
    sa.Column('is_revised', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('billed', sa.Boolean(), nullable=True),
    sa.Column('requestor_email', sa.String(length=255), nullable=True),
    sa.Column('solve_expiration', sa.DateTime(), nullable=True),
    sa.Column('solved_in_time', sa.DateTime(), nullable=True),
    sa.Column('created_by_way_of', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pause_sla_reason', sa.String(length=255), nullable=True),
    sa.Column('pause_sla_stopped', sa.Boolean(), nullable=True),
    sa.Column('attend_sla', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('desk_id', sa.Integer(), nullable=True),
    sa.Column('last_answer_type', sa.String(length=255), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.Column('services_catalog_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banco_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('entity_description', sa.String(length=255), nullable=True),
    sa.Column('menu_item', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['banco_id'], ['postos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('field_type', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('option_name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    op.drop_table('field')
    op.drop_table('entity')
    op.drop_table('postos')
    # ### end Alembic commands ###
